amqp:
  host: "***REMOVED***"
  port: "5672"
  virtualHost: "***REMOVED***"
  username: "***REMOVED***"
  password: "***REMOVED***"
  heartbeatTimeout: "60"
  publisher1:
    exchange: eip-dead_lettering
  listener1:
    queue: backend4-person-main
    max_redelivery_count: "5"
    prefetch:
      size: "1"
      count: "1"
    
amq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  client_id: "***REMOVED***"
  client_secret: "***REMOVED***"
  publisher1:
    exchange: eip-deadlettering
  listener1:
    queue: backend4-person-main
   
http:
  listener:
    basepath: "/dead-lettering"
    port: "8081"
    
api:
  id: "***REMOVED***"